### ISSUE TITLE
API POST request

### ISSUE THREAD

**Issue by johncorderox** [johncorderox/Amy-Winehouse-API#5]
I cannot for the love of god figure out how to do a post request to a rails api from react. 

Know how? I made a little form on the Form.js component. check it out if you ever got time! @capturethemoon

**Comment by capturethemoon** [comment]
I’m not terribly familiar with React on Rails, but I can research this issue and look into it this week!

**Comment by johncorderox** [comment]
awesome man. I tried so many times with online tutorials but i keep getting a strong parameter warning. 

```
NoMethodError (undefined method `song_url' for #<Api::V1::SongsController:0x000000043fe310>
Did you mean?  song_params):
  
app/controllers/api/v1/songs_controller.rb:21:in `create'
Started POST "/api/v1/songs" for 10.0.2.2 at 2018-11-04 05:55:55 +0000
Processing by Api::V1::SongsController#create as */*
  Parameters: {"song_params"=>{"name"=>"fdsafas2", "length"=>"2", "album_id"=>"2"}}
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: song):
```
i tried many things like ``` name="[song]name" ``` and adding song to the ajax post request. let me know what you find.

**Comment by johncorderox** [comment]
will reopen later. closing!

**Comment by capturethemoon** [comment]
Hey, just to give you an update, I still haven't figured out the issue! I will try to do some more research, but I'm not sure if/when I'll have it figured out. 

In the meantime, I had a few questions about the form.js code.  What would happen if, on line 34, you changed `name="[song]albums_id" ` to `name="[song]album_id"`? Also, is there a reason that album_id isn't included as a variable at the top of the code, or in the AJAX post request?

Apologies if these are really basic questions! I'm just trying to understand the form a little better.
